# Generated by Django 4.2.4 on 2023-08-16 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vehicle',
            table='vehicle',
        ),
    ]
